//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtest.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public string Masp { get; set; }
        public string Tensp { get; set; }
        public Nullable<int> Gia { get; set; }
        public string Mota { get; set; }
        public string Hinh { get; set; }
    }
}
